### ISSUE TITLE
Empty in workflow

### ISSUE THREAD

**Issue by Keyu-1218** [olegchomp/TDComfyUI#21]
Hi! Thank you for the amazing job! 
I connect TDComfyUI with workflow_api, however there is no content show in workflow, even I use the example you provide. Sometimes it shows workflow destroyed, can you help me with this?
<img width="1243" alt="image" src="https://github.com/user-attachments/assets/6aedc5c9-b1e8-4e08-880b-bfb96fcc121f">

**Comment by spacepiedra** [comment]
i have the same problem T.T

**Comment by SberVirtualProduction** [comment]
I have the same problem, TD ver. 2023.11600

**Comment by jx666jx** [comment]
I am experiencing the same issue with an empty workflow in the TD properties.
Occasionally the KSampler seed is visible.

TD 2023.12120
ComfyUI v0.3.10
ComfyUI-Manager v2.55.5
ComfyUI Nodes for External Tooling

**Comment by phattiej** [comment]
same issue :(

**Comment by olegchomp** [comment]
Might be version mismatch. Solution should be update ComfyUI with manager or download latest.

**Comment by phattiej** [comment]
Should be the latest version of comfy installed because I just installed today and UI is different from the tutorial video, then made all the updates. I installed ComfyUI manager using git in command prompt. But I'm using TouchDesigner 2023, would that be an issue?

**Comment by olegchomp** [comment]
You might need to export workflow in API format with your ComfyUI version.

**Comment by phattiej** [comment]
I had done that. I also did it again just to be sure ^^, then when I connected the workflow dat to the tox it said workflow destroyed. Still getting the same problem. It shows one slider called ksampler seed.
![Screenshot 2024-12-31 175653](https://github.com/user-attachments/assets/0ad6e8d4-8f07-44d4-b6d9-d4995c107a81)
![Screenshot 2024-12-31 175920](https://github.com/user-attachments/assets/c6d2c490-ed9f-477f-8770-910ec4ce843e)

**Comment by jx666jx** [comment]
FWIW, this on MacOS 15.2.

I have found that whichever input is defined first in the API export, will show up as the 
only par in TD ... likely due to the following error I noticed in TD.

```
Traceback (most recent call last):
  File "/sys/TDResources/webClient/webclient1_callbacks", line 15, in onResponse
  File "/sys/TDResources/webClient/WebClientExt", line 75, in onWebResponse
  File "/project1/TDComfyUI1/TdcomfyEXT", line 243, in callback
  File "/project1/TDComfyUI1/callbackManager/extCallbackManager", line 67, in Do_Callback
  File "/project1/TDComfyUI1/callbackManager/extCallbackManager", line 65, in Do_Callback
  File "/project1/TDComfyUI1/callbackManager/extCallbackManager", line 61, in Execute
  File "/project1/TDComfyUI1/callbackManager/extCallbackManager", line 35, in callbackModule
AttributeError: 'NoneType' object has no attribute 'module'
Traceback (most recent call last):
  File "/sys/TDResources/webClient/webclient1_callbacks", line 12, in onDisconnect
  File "/sys/TDResources/webClient/WebClientExt", line 80, in onWebTimeout
  File "/project1/TDComfyUI1/TdcomfyEXT", line 157, in callback
  File "/Applications/TouchDesigner.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
```

Issue appears to be when the trying to add the workflow pars in TD?

I uncommented 195-198 in TDcomfyEXT, which shows the single workflow variable that was added as a TD par. 
```
    print(jsonPar)
    print(class_title)
    print(inputs[i])
    print(i)

    [['sd3.5_medium.safetensors', 'sd3_medium.safetensors', 'sd3_medium_incl_clips_t5xxlfp16.   safetensors', 'sd_xl_base_1.0.safetensors', 'sd_xl_refiner_1.0.safetensors',   'v1-5-pruned-emaonly.safetensors', 'v2-1_768-ema-pruned.safetensors'], {'tooltip': 'The name  of the checkpoint (model) to load.'}]
    Load Checkpoint
    sd3_medium_incl_clips_t5xxlfp16.safetensors
    ckpt_name
```

I added a print(data) in the TDcomfyEXT load(self) callback function (line 158).
```
    jsonData = json.loads(data)
    print(data)
```
. . . cut . . .
{"default": 0, "min": 0, "max": 16384, "step": 8}], "top": ["INT", {"default": 0, "min": 0, "max": 16384, "step": 8}], "right": ["INT", {"default": 0, "min": 0, "max": 16384, "step": 8}], "bottom": ["INT", {"default": 0, "min": 0, "max": 16384, "step": 8}], "feathering": ["INT", {"default": 40, "min": 0, "max": 16384, "step": 1}]}}, "input_order": {"required": ["image", "left", "top", "right", "bottom", "feathering"]}, "output": ["IMAGE", "MASK"], "output_is_list": [false, false], "output_name": ["IMAGE", "MASK"], "name": "ImagePadForOutpaint", "display_name": "Pad Image for Outpainting", "description": "", "python_module": "nodes", "category": "image", "output_node": false}, "EmptyImage": {"input": {"required": {"width": ["INT", {"default": 512, "min": 1, "max": 16384, "step": 1}], "height": ["INT", {"default": 512, "min": 1, "max": 16384, "step": 1}], "batch_size": ["INT", {"default": 1, "min": 1, "max": 4096}], "color": ["INT", {"default": 0, "min": 0, "max": 16777215, "step": 1, "display": "color"}]}}, "input_order": {"required": ["width", "height", "batch_size", "color"]}, "output": ["IMAGE"],

The data variable appears to be cut short, as it terminates with a ,.

I get this same result when testing different Comfy workflows.

I do get a complete json object with wget http://127.0.0.1:8188/object_info. The output json object is ~205KB.

I am currently trying to understand how the callback functions work and where the issue might lie.  ... it's my first time diving into callbacks ...

**Comment by phattiej** [comment]
I tried what you did and uncommented out the lines 195-198, then I added the line on 158 and I got an error but with the websockets. Though I'm running on windows

![Screenshot 2025-01-06 170410](https://github.com/user-attachments/assets/7938c4fe-c3db-4af0-8a89-8494a8117911)

**Comment by jx666jx** [comment]
Open a textport window to see the print and initial errors when attaching a workflow. 

https://derivative.ca/UserGuide/Textport

**Comment by jx666jx** [comment]
FYI ... updating to ComfyUI version 1.0.8 fixed the issue for me.

Thanks @olegchomp!!!

**Comment by phattiej** [comment]
I did the same just now. Updated ComfyUI, re-added the TD component, and everything started working. It's working great! It's a bit slower streaming than the stream diffusion component. But happy it works. Thanks @olegchomp !
